export const menu = [
  {
    label: 3,
    children: [
      {
        label: '关门启动速度',
        value: '',
        visible: true,
        num: 100,
      }, {
        'label': '关门高速',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '速度稳定时允许误差频率',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '同步门门刀打开速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '关门低速 1 ',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '关门低速 2 ',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '开门启动速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '开门高速',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '开门低速 1 ',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '开门高速 2 ',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '自学习及上电运行速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '开门限位时保持速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '关门限位时保持速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '低速区启动时运行速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '同步电机上电时运行速度',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '加减速时允许误差频率',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '最大输出频率',
        'value': '',
        'visible': true,
        num: 100,
      }, {
        'label': '基准频率',
        'value': '',
        'visible': true,
        num: 100,
      },
    ]
  },
  {
    'label': 4,
    'children': [
      {
        'label': '加速时间',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '减速时间',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '启动时 S 曲线',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '到达时 S 曲线',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '开门停止保护时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '关门停止保护时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': 'IPM 故障电机关断时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '每分钟允许故障次数',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '门机急停时减速时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '门逆转延时时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '制动力保持时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '检测电流滤波时间',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '测试运行时开关门总时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '关门过流允许时间',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '开门过流允许时间',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '关门过流继电器动作时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '飞车保护起作用延时时间设定',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '关门到位输出延时时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '允许开、关门运行时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '过电流电机关断时间',
        'value': '',
        'visible': true,
        num: 10
      }, {
        'label': '给定速度滤波时间',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '检测速度滤波时间',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '输出滤波时间',
        'value': '',
        'visible': true,
        num: 1
      },
    ]
  }, {
    'label': 5,
    'children': [
      {
        'label': '开门减速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门减速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门极限位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门极限位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开锁速度运行距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门启动速度运行距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '安全触板限位距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '门宽距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门低速区距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门低速区距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '同步门刀打开时加速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '同步门刀打开时减速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '低速区启动开门时减速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '低速区启动关门时减速距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门过流检测距离',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门限位保护位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门 限位保护位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门低速 1 减速位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门低速 1 减速位置',
        'value': '',
        'visible': true,
        num: 1
      },
    ]
  }, {
    'label': 6,
    'children': [
      {
        'label': '低速力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '高速力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '开门保持力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '关门保持力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '同步电机启动运行电压',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '开门最大力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '关门最大力矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '稳定运行时关门过载电流',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '开、关门过载保护电流',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '加减速运行时关门过载电流',
        'value': '',
        'visible': true,
        num: 100
      },
    ]
  }, {
    'label': 7,
    'children': [
      {
        'label': '最大转矩',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '过流电流的减少量',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '关门保持力矩 1 ',
        'value': '',
        'visible': true,
        num: 100
      }, {
        'label': '电流传感器 U 相零点电流偏移',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '电流传感器 V 相零点电流偏移',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '电流传感器电流比例',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '速度环 P 参数',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '速度环 I 参数',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '励磁电流环 P 参数',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '励磁电流环 I 参数',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '力矩电流环 P 参数',
        'value': '',
        'visible': true,
        num: 1
      },{
        'label': '力矩电流环 I 参数',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门高速力矩限定',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '菜单调节演示',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '同步电机磁极位置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '编码器每转脉冲数',
        'value': '',
        'visible': true,
        num: 1
      },
    ]
  }, {
    'label': 8,
    'children': [
      {
        'label': '同步门选择设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '电机 UVW 接线方向设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '门机测试运行设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '门宽自测定设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '数据初始化设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '磁极位置测定操作',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '数据写保护设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门制动定时/长期制动选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门制动定时/长期制动选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '编码器方向设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门过载反开动作设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '控制模式设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '消防功能选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门限位输出继电器极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门限位输出继电器极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门限位开关极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门限位开关极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '电机温控开关极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '光幕极性设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '电机级数设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门输入信号端子选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门输入信号端子选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '开门限位输入信号端子选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门限位输入信号端子选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '保留',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '消防输入信号端子选择',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '前后门设置',
        'value': '',
        'visible': true,
        num: 1
      }, {
        'label': '关门自动检测停止位置设置',
        'value': '',
        'visible': true,
        num: 1
      }
    ]
  }
];
